[api_envi]
host = http://127.0.0.1:8787

[MYSQL]
host = 127.0.0.1
port = 3306
username =
password =
database =

[REDIS]
host = 127.0.0.1
port = 6379
username =
password =
db = 0

[CLICKHOUSE]
host = 127.0.0.1
port = 8123
username = default
password =
timeout = 10
db = default

[MongoDB]
host = 127.0.0.1
port = 27017
username =
password =
database =

[EMAIL]
host =
port = 465
user =
passwd =
addressee =
subject =

[SSH]
host =
port = 22
username =
password =
timeout = 10
command =

; 默认为allure；若设为tm，则生成tmreport报告。
[REPORT_TYPE]
type = allure
